// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-m3d6IkOBbjFGRHRVMzwdIYmdptxzh4',
    appId: '1:573448307022:web:e666a083a0d16bc6b39e1f',
    messagingSenderId: '573448307022',
    projectId: 'kenexpress-883d3',
    authDomain: 'kenexpress-883d3.firebaseapp.com',
    storageBucket: 'kenexpress-883d3.firebasestorage.app',
    measurementId: 'G-V77SYM9NQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1uE8oFGM8YN8VfUtCzyhpWaU6_0dMPhE',
    appId: '1:573448307022:android:c8dd6bf7dc1f399eb39e1f',
    messagingSenderId: '573448307022',
    projectId: 'kenexpress-883d3',
    storageBucket: 'kenexpress-883d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmSLAFGsjmeSdySM_lR8tdDEoxjhQNxYs',
    appId: '1:573448307022:ios:99df9db4171831e2b39e1f',
    messagingSenderId: '573448307022',
    projectId: 'kenexpress-883d3',
    storageBucket: 'kenexpress-883d3.firebasestorage.app',
    iosBundleId: 'com.example.kenExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmSLAFGsjmeSdySM_lR8tdDEoxjhQNxYs',
    appId: '1:573448307022:ios:99df9db4171831e2b39e1f',
    messagingSenderId: '573448307022',
    projectId: 'kenexpress-883d3',
    storageBucket: 'kenexpress-883d3.firebasestorage.app',
    iosBundleId: 'com.example.kenExpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1-m3d6IkOBbjFGRHRVMzwdIYmdptxzh4',
    appId: '1:573448307022:web:36ba4e72c51dbf69b39e1f',
    messagingSenderId: '573448307022',
    projectId: 'kenexpress-883d3',
    authDomain: 'kenexpress-883d3.firebaseapp.com',
    storageBucket: 'kenexpress-883d3.firebasestorage.app',
    measurementId: 'G-Q69L2EKVHQ',
  );
}
